## Part I
#### Inspecting datasets

In [147]:
import pandas as pd
import numpy as np

In [148]:
'''Set display option'''
pd.set_option('display.max_rows', 15)
pd.set_option('display.max_columns', 100)

In [149]:
irv_urb = pd.read_csv('data/irvine_ca_city_2.csv')
irv_sub = pd.read_csv('data/irvine_ca_suburb_2.csv')
san_diego_urb = pd.read_csv('data/san_diego_ca_city_2.csv')
san_diego_sub = pd.read_csv('data/san_diego_ca_suburb_2.csv')
san_fran_urb = pd.read_csv('data/san_francisco_ca_city_2.csv')
san_fran_sub = pd.read_csv('data/san_francisco_ca_suburb_2.csv')

In [150]:
irv_urb

,month_date_yyyymm,postal_code,zip_name,nielsen_hh_rank,hotness_rank,hotness_rank_mm,hotness_rank_yy,hotness_score,supply_score,demand_score,median_days_on_market,median_days_on_market_mm,median_dom_mm_day,median_days_on_market_yy,median_dom_yy_day,median_dom_vs_us,ldp_unique_viewers_per_property_mm,ldp_unique_viewers_per_property_yy,ldp_unique_viewers_per_property_vs_us,median_listing_price,median_listing_price_mm,median_listing_price_yy,median_listing_price_vs_us,quality_flag,id,zip_code
0,202201,92618,"irvine, ca",4109,1772,-606.0,5647.0,74.641195,95.077580,54.204810,16.0,-0.200000,-4.0,-0.666667,-32.0,-45.0,0.272085,2.159184,1.1166,1300975.0,-0.066665,0.131283,3.4693,1,1,92618
1,202201,92620,"irvine, ca",1262,1177,-879.0,2803.0,79.059348,89.394880,68.723817,30.0,0.052632,1.5,-0.166667,-6.0,-31.0,0.051184,0.810042,1.4500,1475000.0,0.068841,0.172496,3.9333,0,2,92620
2,202112,92618,"irvine, ca",4109,1166,93.0,7128.0,78.240454,95.304529,61.176380,20.0,-0.148936,-3.5,-0.619048,-32.5,-33.5,-0.105122,2.856531,1.2792,1393900.0,0.056735,0.212087,3.7171,1,1,92618
3,202111,92602,"irvine, ca",4786,3534,1342.0,6541.0,61.266337,70.898011,51.634663,38.5,-0.197917,-9.5,-0.496732,-38.0,-8.0,-0.148893,1.659151,1.1203,2300000.0,0.008772,0.473136,6.0614,1,5,92602
4,202111,92612,"irvine, ca",2307,2849,312.0,5521.0,65.066498,70.066306,60.066690,39.0,0.114286,4.0,-0.195876,-9.5,-7.5,0.054562,2.557075,1.2897,987500.0,0.012821,0.371528,2.6025,1,3,92612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,201708,92602,"irvine, ca",4786,4093,NaN,NaN,64.323612,87.730982,40.916243,36.0,NaN,NaN,NaN,NaN,-30.5,NaN,NaN,0.8637,1618950.0,NaN,NaN,5.8027,1,5,92602
256,201708,92603,"irvine, ca",5600,5906,NaN,NaN,53.593253,67.119177,40.067328,57.0,NaN,NaN,NaN,NaN,-9.5,NaN,NaN,0.8500,2124500.0,NaN,NaN,7.6147,0,6,92603
257,201708,92612,"irvine, ca",2307,3260,NaN,NaN,69.040214,90.369205,47.711223,32.5,NaN,NaN,NaN,NaN,-34.0,NaN,NaN,0.9716,867000.0,NaN,NaN,3.1075,0,3,92612
258,201708,92618,"irvine, ca",4109,3326,NaN,NaN,68.571847,90.844890,46.298803,32.0,NaN,NaN,NaN,NaN,-34.5,NaN,NaN,0.9471,950000.0,NaN,NaN,3.4050,0,1,92618
259,201708,92620,"irvine, ca",1262,2999,NaN,NaN,70.701453,93.548977,47.853928,27.5,NaN,NaN,NaN,NaN,-39.0,NaN,NaN,0.9742,1024344.0,NaN,NaN,3.6715,0,2,92620

### Check empty fields for each col in every dataset

In [151]:
tmp_1 = irv_urb.isnull().any()
print('irv_urb fields with empty values')
print('-------------------------------')
print(tmp_1[tmp_1])
print()

tmp_2 = irv_sub.isnull().any()
print('-------------------------------')
print('irv_sub fields with empty values')
print(tmp_2[tmp_2])
print()

tmp = san_diego_urb.isnull().any()
print('-------------------------------')
print('san_diego_urb fields with empty values')
print(tmp[tmp])
print()

tmp = san_diego_sub.isnull().any()
print('-------------------------------')
print('san_diego_sub fields with empty values')
print(tmp[tmp])
print()

tmp = san_fran_urb.isnull().any()
print('-------------------------------')
print('san_fran_urb fields with empty values')
print(tmp[tmp])
print()

tmp = san_fran_sub.isnull().any()
print('-------------------------------')
print('san_fran_sub fields with empty values')
print(tmp[tmp])
print()

irv_urb fields with empty values
-------------------------------
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
irv_sub fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
san_diego_urb fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
san_diego_sub fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
san_fran_urb fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
san_fran_sub fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

From above, there's not much info so after manual inspection, I confirmed that all datasets have the 
same fields that have empty values. And none of the fields are the critical ones that must not be dropped.

In [152]:
'''drop incomplete (bc they are also not necessary) columns'''

to_drop = ['hotness_rank_mm', 'hotness_rank_yy', 'median_days_on_market_mm', 'median_dom_mm_day', 'median_days_on_market_yy',
    'median_dom_yy_day', 'ldp_unique_viewers_per_property_mm', 'ldp_unique_viewers_per_property_yy',
    'median_listing_price_mm', 'median_listing_price_yy']

irv_sub = irv_sub.drop(to_drop, axis=1)
irv_urb = irv_urb.drop(to_drop, axis=1)
san_diego_sub = san_diego_sub.drop(to_drop, axis=1)
san_diego_urb = san_diego_urb.drop(to_drop, axis=1)
san_fran_urb = san_fran_urb.drop(to_drop, axis=1)
san_fran_sub = san_fran_sub.drop(to_drop, axis=1)

## Part II
#### Incorporate population density

In [153]:
'''
concatenate original urban and suburban datasets
and rename zip code code col to zipcode
'''

irv = pd.concat([irv_urb, irv_sub])
irv = irv.rename({'zip_code': 'zipcode'}, axis=1)

san_diego = pd.concat([san_diego_urb, san_diego_sub])
san_diego = san_diego.rename({'zip_code': 'zipcode'}, axis=1)

san_fran = pd.concat([san_fran_urb, san_fran_sub])
san_fran = san_fran.rename({'zip_code': 'zipcode'}, axis=1)

san_fran.describe()

,month_date_yyyymm,postal_code,nielsen_hh_rank,hotness_rank,hotness_score,supply_score,demand_score,median_days_on_market,median_dom_vs_us,ldp_unique_viewers_per_property_vs_us,median_listing_price,median_listing_price_vs_us,quality_flag,id,zipcode
count,2431.000000,2431.000000,2431.000000,2431.000000,2431.000000,2431.000000,2431.000000,2431.000000,2431.000000,2431.000000,2.431000e+03,2431.000000,2431.000000,2431.000000,2431.000000
mean,201943.897573,94557.116413,2547.639243,2953.908680,70.509833,82.944875,58.074790,33.771082,-27.339161,1.543934,1.146701e+06,3.546118,0.495681,28.603455,94557.116413
std,126.900625,408.076737,1925.859675,2786.313915,19.372599,14.880992,28.740588,14.528132,17.965108,0.962488,5.177294e+05,1.663211,0.500084,21.461572,408.076737
min,201708.000000,94085.000000,14.000000,1.000000,12.143986,18.356080,0.908359,5.500000,-84.500000,0.149500,3.750000e+05,1.306800,0.000000,1.000000,94085.000000
25%,201811.000000,94116.000000,1017.000000,579.000000,56.567730,76.276527,32.720746,23.500000,-39.500000,0.814250,7.666964e+05,2.327300,0.000000,11.000000,94116.000000
50%,201911.000000,94602.000000,1901.000000,1990.000000,73.904716,88.151037,62.073418,31.000000,-29.000000,1.301600,1.035286e+06,3.210700,0.000000,22.000000,94602.000000
75%,202012.000000,95110.000000,4053.000000,4690.500000,87.279257,93.927641,84.734410,41.000000,-15.000000,2.075650,1.422250e+06,4.419100,1.000000,53.000000,95110.000000
max,202201.000000,95136.000000,7926.000000,11078.000000,98.733946,99.330448,99.293790,102.000000,50.000000,6.461100,4.545000e+06,15.155100,1.000000,68.000000,95136.000000

In [154]:
'''read in population density file'''
pop_dens = pd.read_csv('./data/population_density/2020_population_density_by_zipcode.csv')

FileNotFoundError: [Errno 2] No such file or directory: './data/population_density/2020_population_density_by_zipcode.csv'

In [ ]:
pop_dens

       ZCTA  population  area (sq mi)  pop_density
0     89010         469       404.233     1.160222
1     89019        2068       478.048     4.325925
2     89060       10692       462.549    23.115389
3     89061        5537        72.710    76.151836
4     89439        1244        14.579    85.328212
...     ...         ...           ...          ...
1764  96148         679         1.360   499.264706
1765  96150       30369       123.542   245.819236
1766  96155           0        37.043     0.000000
1767  96161       18782       181.839   103.289173
1768  97635         164        44.799     3.660796

[1769 rows x 4 columns]

In [ ]:
pop_dens.describe()

               ZCTA     population  area (sq mi)   pop_density
count   1769.000000    1769.000000   1769.000000   1769.000000
mean   93652.261164   22248.884681     60.232749   3419.037483
std     1831.334177   22598.308562    112.614525   5582.005939
min    89010.000000       0.000000      0.006000      0.000000
25%    92253.000000    1513.000000      5.047000     44.603593
50%    93654.000000   15974.000000     15.945000    721.362229
75%    95379.000000   36820.000000     69.079000   5116.342412
max    97635.000000  110750.000000   1395.018000  56174.943567

In [ ]:
# number of zip codes that have population = 0 (maybe PO Box)
(pop_dens['population'] == 0).sum()

28

In [ ]:
'''prepare the zip codes for all three cities'''
irv_zips = [
    92618, 92620, 92602, 92612, 92603, 92692, 
    92629, 92886, 92660, 92656, 92691, 92677, 
    92672, 92688, 92867]

san_diego_zips = [   
    92103, 92115, 92104, 92111, 92110, 92105,
    92120, 92122, 92102, 92106, 92126, 92107,
    92127, 92117, 92131, 92108, 92116, 92130,
    92101, 92118, 92129, 92119, 92113, 92154,
    92128, 92109, 92114, 92139, 92123,
    91911, 92040, 92019, 91935, 91945, 92075, 
    91910, 91913, 91977, 92021, 92037, 92064, 
    91950, 91914, 91915, 91942, 91932, 92067, 
    92014, 92118, 91902, 92071, 91941, 92020, 
    91901]

san_fran_zips = [
    94105, 94121, 94124, 94109, 94116, 94134, 
    94115, 94131, 94112, 94133, 94118, 94103, 
    94123, 94114, 94107, 94108, 94110, 94102, 
    94619, 94611, 94606, 94595, 94610, 94801, 
    94804, 94621, 94603, 94605, 94607, 94601, 
    94596, 95127, 95126, 95112, 95110, 94598, 
    94602, 95136, 94087, 94086, 95123, 95128, 
    95125, 95124, 94618, 95132, 94588, 94085, 
    95118, 95120, 95116, 95131, 95135]

In [ ]:
# test an Irvine zip code
92618 in pop_dens.ZCTA.values

True

In [ ]:
'''join market data with population density'''
irv_pop_dens = irv.set_index('zipcode').join(pop_dens.set_index('zipcode'))
san_diego_pop_dens = san_diego.set_index('zipcode').join(pop_dens.set_index('zipcode'))
san_fran_pop_dens = san_fran.set_index('zipcode').join(pop_dens.set_index('zipcode'))
# san_diego_pop_dens.describe()

#### Add a calculated column, population density
NOTE: We can also use "grouping" in Tableau to achieve same result. Since these data are going to be fed to Tableau where most analysis/vizzes are performed, I will leave this field out of this pre-processed data and do the liftings there, in which case there's even more flexibility

In [ ]:
'''definition of density level'''
high = 6500
mid = 3000

'''add density level column according to predefined threshold values'''

conditions = [
    (san_diego_pop_dens['pop_density'] >= high),
    ((san_diego_pop_dens['pop_density'] < high) & (san_diego_pop_dens['pop_density'] >= mid)),
    (san_diego_pop_dens['pop_density'] < mid)
]

values = ['high', 'mid', 'low']

'''comment out to perform the task'''
# san_diego_pop_dens['density_lv'] = np.select(conditions, values)
# san_diego_pop_dens

'comment out to perform the task'

#### Export

In [155]:
'''export to csv'''
irv.to_csv('./data/clean_data/irvine.csv')
san_diego_pop_dens.to_csv('./data/clean_data/san_diego.csv')
san_fran_pop_dens.to_csv('./data/clean_data/san_francisco.csv')

In [158]:
tmp = pd.read_csv('./data/clean_data/san_diego.csv')
tmp

,zipcode,month_date_yyyymm,postal_code,zip_name,nielsen_hh_rank,hotness_rank,hotness_score,supply_score,demand_score,median_days_on_market,median_dom_vs_us,ldp_unique_viewers_per_property_vs_us,median_listing_price,median_listing_price_vs_us,quality_flag,id,population,area (sq mi),pop_density
0,91901,202008,91901,"alpine, ca",6796,1946,72.998360,84.449083,61.547637,29.0,-24.0,1.3241,875000.0,2.5000,0,1,17403,89.357,194.758105
1,91901,202009,91901,"alpine, ca",6796,2741,68.254717,87.007547,49.501887,25.0,-26.0,1.0757,774000.0,2.2114,0,1,17403,89.357,194.758105
2,91901,202010,91901,"alpine, ca",6796,1986,72.679869,90.956666,54.403072,21.0,-30.0,1.1660,819000.0,2.3400,1,1,17403,89.357,194.758105
3,91901,202011,91901,"alpine, ca",6796,3240,65.177822,75.665878,54.689766,39.5,-17.0,1.1819,812000.0,2.3250,0,1,17403,89.357,194.758105
4,91901,202012,91901,"alpine, ca",6796,688,84.225266,92.841524,75.609008,28.0,-36.0,1.6970,822000.0,2.4105,0,1,17403,89.357,194.758105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2724,92154,201806,92154,"san diego, ca",409,432,89.737697,91.674875,87.800518,24.0,-33.0,2.2351,499000.0,1.6633,1,30,79708,37.169,2144.475235
2725,92154,201807,92154,"san diego, ca",409,489,88.357718,96.009510,80.705925,20.5,-39.0,1.8225,520000.0,1.7339,0,30,79708,37.169,2144.475235
2726,92154,201808,92154,"san diego, ca",409,424,88.628567,96.763010,80.494125,20.0,-42.0,1.8087,523775.0,1.7503,1,30,79708,37.169,2144.475235
2727,92154,201809,92154,"san diego, ca",409,697,85.072917,95.555879,74.589955,25.0,-40.0,1.5869,500000.0,1.6722,0,30,79708,37.169,2144.475235
2728,92154,201810,92154,"san diego, ca",409,704,84.625351,94.262564,74.988138,29.5,-39.0,1.6202,489500.0,1.6371,0,30,79708,37.169,2144.475235