## Part I
#### Inspecting datasets

In [1]:
import pandas as pd

In [13]:
irv_urb = pd.read_csv('data/irvine_ca_city_2.csv')
irv_sub = pd.read_csv('data/irvine_ca_suburb_2.csv')
san_diego_urb = pd.read_csv('data/san_diego_ca_city_2.csv')
san_diego_sub = pd.read_csv('data/san_diego_ca_suburb_2.csv')
san_fran_urb = pd.read_csv('data/san_francisco_ca_city_2.csv')
san_fran_sub = pd.read_csv('data/san_francisco_ca_suburb_2.csv')

In [7]:
irv_urb.head()
irv_urb.describe()

,month_date_yyyymm,postal_code,nielsen_hh_rank,hotness_rank,hotness_rank_mm,hotness_rank_yy,hotness_score,supply_score,demand_score,median_days_on_market,...,ldp_unique_viewers_per_property_mm,ldp_unique_viewers_per_property_yy,ldp_unique_viewers_per_property_vs_us,median_listing_price,median_listing_price_mm,median_listing_price_yy,median_listing_price_vs_us,quality_flag,id,zip_code
count,260.000000,260.000000,260.000000,260.000000,200.0000,200.000000,260.000000,260.000000,260.000000,260.000000,...,200.000000,200.000000,260.000000,2.600000e+02,200.000000,200.000000,260.000000,260.000000,260.000000,260.000000
mean,201930.507692,92611.119231,3604.461538,6149.011538,45.0450,-546.120000,50.263809,72.464891,28.062727,46.967308,...,0.056371,0.609354,0.720379,1.384905e+06,0.009623,0.054538,4.320238,0.415385,3.365385,92611.119231
std,128.817715,7.430840,1597.418804,1983.954556,937.8954,2435.233664,12.065978,14.530400,15.607292,16.878223,...,0.169008,0.849368,0.244935,6.284740e+05,0.081752,0.207857,1.884994,0.493739,1.860262,7.430840
min,201708.000000,92602.000000,1262.000000,985.000000,-2097.0000,-5564.000000,25.022896,27.739183,3.042054,13.500000,...,-0.292261,-0.565554,0.249100,7.180000e+05,-0.257499,-0.302189,2.061600,0.000000,1.000000,92602.000000
25%,201808.750000,92603.000000,2307.000000,4875.750000,-569.2500,-2298.250000,40.475329,63.884360,15.524741,34.000000,...,-0.056085,-0.146249,0.541725,1.024607e+06,-0.019691,-0.070231,3.153050,0.000000,2.000000,92603.000000
50%,201909.500000,92612.000000,4109.000000,6365.000000,22.0000,-557.500000,49.108329,71.872231,24.512551,44.500000,...,0.023449,0.532630,0.663500,1.188720e+06,0.000277,0.033344,3.702750,0.000000,3.000000,92612.000000
75%,202010.250000,92618.000000,4786.000000,7710.750000,580.5000,773.750000,57.335391,84.513212,40.141039,57.125000,...,0.129112,1.124492,0.882325,1.565096e+06,0.029394,0.122104,4.749300,1.000000,5.000000,92618.000000
max,202201.000000,92620.000000,5600.000000,10075.000000,4119.0000,7801.000000,79.808012,96.656299,68.723817,100.000000,...,0.765795,4.291544,1.450000,4.334000e+06,0.689392,1.436885,11.646300,1.000000,6.000000,92620.000000

### Check empty fields for each col in every dataset

In [25]:
tmp_1 = irv_urb.isnull().any()
print('irv_urb fields with empty values')
print('-------------------------------')
print(tmp_1[tmp_1])
print()

tmp_2 = irv_sub.isnull().any()
print('-------------------------------')
print('irv_sub fields with empty values')
print(tmp_2[tmp_2])
print()

tmp = san_diego_urb.isnull().any()
print('-------------------------------')
print('san_diego_urb fields with empty values')
print(tmp[tmp])
print()

tmp = san_diego_sub.isnull().any()
print('-------------------------------')
print('san_diego_sub fields with empty values')
print(tmp[tmp])
print()

tmp = san_fran_urb.isnull().any()
print('-------------------------------')
print('san_fran_urb fields with empty values')
print(tmp[tmp])
print()

tmp = san_fran_sub.isnull().any()
print('-------------------------------')
print('san_fran_sub fields with empty values')
print(tmp[tmp])
print()

irv_urb fields with empty values
-------------------------------
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
irv_sub fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
san_diego_urb fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
san_diego_sub fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
san_fran_urb fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

-------------------------------
san_fran_sub fields with empty values
hotness_rank_mm                       True
hotness_rank_yy                       True
median_days_on_market_mm              True
median_dom_mm_day                     True
median_days_on_market_yy              True
median_dom_yy_day                     True
ldp_unique_viewers_per_property_mm    True
ldp_unique_viewers_per_property_yy    True
median_listing_price_mm               True
median_listing_price_yy               True
dtype: bool

From above, there's not much info so after manual inspection, I confirmed that all datasets have the 
same fields that have empty values. And none of the fields are the critical ones that must not be dropped.

## Part II
#### Incorporate population density

In [37]:
'''read in population density file'''
pop_dens = pd.read_csv('./data/population_density/population_density_by_zipcode.csv')

In [38]:
pop_dens

       zipcode  population  area (sq mi)  pop_density
0        20052         470         0.003  156666.6667
1        20390         584         0.004  146000.0000
2        10028       45141         0.313  144220.4473
3        10075       26121         0.184  141961.9565
4        10162        1685         0.012  140416.6667
...        ...         ...           ...          ...
33114    20260           0         0.018       0.0000
33115    10172           0         0.005       0.0000
33116    98174           0         0.004       0.0000
33117    20202           0         0.007       0.0000
33118    40231           0         0.084       0.0000

[33119 rows x 4 columns]

In [42]:
# number of zip codes that have population = 0 (maybe PO Box)
(pop_dens['population'] == 0).sum()

144